version: "3"
services:
  myapp:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - testDbIp=mariadb
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - nat
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: gram__test

    ports:
      - "3306:3306"

    networks:
      - nat

networks:
  nat:
    external: true
