global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] #프로메테우스 자기 자신 호출


  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000'] #그라파나 호출


  - job_name: 'my-spring'
    scrape_interval: 5s
    static_configs:
      - targets: ['myapp:8080'] #실제 서비스 호출